# Generated by Django 4.1.2 on 2022-11-06 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cpf', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(max_length=25)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.courier')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('cpnj', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=1)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.delivery')),
            ],
        ),
    ]
